<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net480</TargetFramework>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="System.Net.Http.Experimental.SocketsHttpHandlerFW.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(CoreLibSharedDir)System\Runtime\CompilerServices\IsExternalInit.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="$(SystemThreadingTasksExtensionsVersion)" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
