<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(CoreLibSharedDir)System\Runtime\CompilerServices\IsExternalInit.cs" />
    <Compile Include="Http2Test.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\System.Net.Http.Experimental.SocketsHttpHandlerFW.csproj" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
